export interface LoginResponseInterface {
  // token??: string
  // token_type??: string
  // expires_in?: number
  // user??: {
  //   id??: number,
  //   username??: string,
  //   email??: string,
  //   role_id??: number,
  //   satuan_kerja_id??: string
  // }


  token?: string,
  token_type?: string,
  expires_in?: number,
  user?: {
    id?: number,
    username?: string,
    email?: any,
    role_id?: number,
    satuan_kerja_id?: string,
    deleted_at?: null,
    created_at?: string,
    updated_at?: string,
    nama?: string,
    unit_kerja_id?: string,
    status_aktif?: number,
    roles?: string[],
    cabang_pendidikan?: any,
    pegawai?: {
      peg_id?: string,
      last_update?: string,
      peg_nip?: string,
      peg_nip_lama?: string,
      peg_nama?: string,
      peg_nama_lengkap?: string,
      peg_lahir_tanggal?: string,
      peg_usia?: number,
      peg_jenis_kelamin?: string,
      peg_rumah_alamat?: string,
      peg_kodepos?: string,
      peg_foto_url?: string,
      peg_status?: boolean,
      peg_ketstatus?: any,
      peg_ktp?: string,
      peg_umur_pensiun?: number,
      peg_jabatan_tmt?: string,
      peg_eselon_tmt?: any,
      peg_skpd_tmt?:string,
      peg_npwp?: string,
      peg_telp?: string,
      peg_telp_hp?: string,
      id_agama?: number,
      nm_agama?:string,
      jabatan_id?: number,
      jf_id?: number,
      jfu_id?:any,
      jabatan_jenis?: number,
      jabatan_nama?: string,
      eselon_id?: any,
      eselon_nm?: any,
      unit_kerja_id?: string,
      unit_kerja_nama?: string,
      satuan_kerja_id?: string,
      satuan_kerja_nama?: string,
      gol_id_awal?: number,
      nm_gol_awal?: string,
      nm_pkt_awal?: string,
      gol_id_akhir?: number,
      nm_gol_akhir?: string,
      nm_pkt_akhir?: string,
      id_pend_awal?: number,
      nm_pend_awal?: string,
      kat_nama_pend_awal?:string,
      nm_tingpend_awal?: string,
      id_pend_akhir?: number,
      nm_pend_akhir?: string,
      kat_nama_pend_akhir?: string,
      nm_tingpend_akhir?: string,
      riwayat_pendidikan?: string,
      riwayat_jabatan?: string,
      unit_kerja_parent_nama?: string,
      kedudukan_pegawai?: any,
      kedudukan_pns?: string,
      kode_jabatan?: any,
      peg_tmt_pensiun?: string,
      masa_kerja_tahun?: number,
      masa_kerja_bulan?: number,
      masa_kerja_golongan_tahun?: number,
      masa_kerja_golongan_bulan?: number,
      peg_status_kepegawaian_id?: number,
      peg_status_kepegawaian?:string,
      tugas_tambahan_jabatan_id?: any,
      tugas_tambahan_jenis?: any,
      daftar_spesialisasi?: any,
      tugas_tambahan_jabatan_nama?: any,
      tmt_tugas_tambahan?: any,
      peg_instansi_dpk?: any,
      daftar_spesialisasi_nama?: any,
      peg_jenis_pns?: number,
      jf_nama?: string,
      jfu_nama?: any,
      peg_gol_akhir_tmt?: string,
      peg_ketstatus_tgl?: any,
      peg_cpns_tmt?: string,
      peg_pns_tmt?: any,
      nuptk?: any,
      id_goldar?: number,
      nm_goldar?: string,
      peg_email?: string,
      peg_bapertarum?: any,
      peg_no_askes?: string,
      id_status_kepegawaian?: number,
      peg_lahir_tempat?: string,
      peg_status_perkawinan?: number,
      unit_kerja_level?: number,
      unit_kerja_parent?:string,
      peg_kel_desa?: any,
      kecamatan_nm?: any,
      jabatan_kelas?: any,
      peg_karpeg?: any,
      peg_pend_akhir_th?:string,
      peg_nama_jenis_pns?: string,
      peg_jft_tmt?: string,
      id_kota?: number,
      id_kec?: number,
      id_kel?: number,
      id_provinsi?: number,
      nama_kel?: string,
      nama_kec?: string,
      nama_kota?: string,
      nama_provinsi?: string,
      tugas_tambahan2_jabatan_id?: any,
      tugas_tambahan2_jenis?: any,
      tugas_tambahan2_jabatan_nama?: any,
      tmt_tugas_tambahan2?: any,
      peg_alamat_latitude?: any,
      peg_alamat_longitude?: any,
      is_gtk?: boolean,
      peg_alamat_rt?: string,
      peg_alamat_rw?: string,
      peg_alamat_rt_ktp?: string,
      peg_alamat_rw_ktp?: string,
      peg_rumah_alamat_ktp?: string,
      peg_kodepos_ktp?: string,
      nama_kel_ktp?: string,
      nama_kec_ktp?: string,
      nama_kota_ktp?: string,
      nama_provinsi_ktp?: string,
      nip_atasan?: string,
      nama_atasan?:string,
      nip_atasan_bayangan?: string,
      nama_atasan_bayangan?: string,
      peg_kgb_yad_akhir?: any,
      unit_kerja_nama_full?: string,
      organisasi_nama_alias?: string,
      organisasi_id?: string,
      peg_no_rekening?: any,
      peg_masa_kerja_golongan?: any,
      peg_jumlah_anak?: number,
      peg_jumlah_anak_tunjangan?: number,
      peg_jumlah_pasangan_tunjangan?: number,
      peg_email_resmi?: any,
      tanggal_lahir_origin?:string,
      tanggal_cpns_origin?: string,
      tanggal_pns_origin?: any,
      tmt_golongan_akhir_origin?: string,
      foto_pegawai_environment?:string,
      perhitungan_umur?: {
        y?: number,
        m?: number,
        d?: number,
        h?: number,
        i?: number,
        s?: number,
        f?: number,
        weekday?: number,
        weekday_behavior?: number,
        first_last_day_of?: number,
        invert?: number,
        days?: number,
        special_type?: number,
        special_amount?: number,
        have_weekday_relative?: number,
        have_special_relative?: number
      },
      masa_kerja_nip?: {
        y?: number,
        m?: number,
        d?: number,
        h?: number,
        i?: number,
        s?: number,
        f?: number,
        weekday?: number,
        weekday_behavior?: number,
        first_last_day_of?: number,
        invert?: number,
        days?:number,
        special_type?:number,
        special_amount?: number,
        have_weekday_relative?: number,
        have_special_relative?: number,
      },
      masa_kerja_golongan_akhir?: {
        y?: number,
        m?: number,
        d?: number,
        h?: number,
        i?: number,
        s?: number,
        f?: number,
        weekday?: number,
        weekday_behavior?: number,
        first_last_day_of?: number,
        invert?: number,
        days?: number,
        special_type?: number,
        special_amount?: number,
        have_weekday_relative?: number,
        have_special_relative?: number,
      },
      golongan_pensiun?: number,
      usulan?: any
    },
    skpd_role?: {
      id?: number,
      role_name?: string,
      created_at?: any,
      updated_at?: any
    }
  }

}